### ISSUE TITLE
Possible Error in Code

### ISSUE THREAD

**Issue by jrjefferies** [jamesleesaunders/Hive-SmartPlug-XBee#3]
This piece of code has helped me no end.  I now have confidence that getting my Alertme kit to work without alertme cloud servers is possible.  This code (or an earlier version) is working for me, but I have some questions.
The hive-smartplug-xbee.py has two elif statements that match the same cluster message
elif (clusterId == '\x00\x06'):

The first sends
- Send Active Endpoint Request (ZDP_PROFILE_ID)
- Sent Match Description Response (ZDP_PROFILE_ID)

The second sends
- Device Discover (ALERTME_PROFILE_ID)
- Device Status (ALERTME_PROFILE_ID)

I can't see how the second bit of code ever gets called.  Is this just an error?  I ask, as I am now trying to get your PyAlertMe working, and I am having trouble with the plugs not joining the network properly.

**Comment by jamesleesaunders** [comment]
Thanks for pointing out! I think the second elsif was erroneous. It is meant to send 4 messages in one hit:
- Active Endpoint Request
- Match Descriptor
- Hardware Join 1
- Hardware Join 2

I have fixed the code.

You may also be interested in https://github.com/jamesleesaunders/PyAlertMe
